### ISSUE TITLE
Please reconsider clashing name

### ISSUE THREAD

**Issue by Harleqin** [FiV0/cl-elasticsearch#1]
Since you already know that there is a different library for the same purpose with the same name, wouldn't it make sense to find a different name to avoid confusion?

**Comment by FiV0** [comment]
I thought as the other one is not in quicklisp and also (afaik) never was it wouldn't be to big of an issue, but if you think it's bad I can rename it. Does `cl-elastic` work for you?

**Comment by Harleqin** [comment]
Being in Quicklisp is not a sign of maturity or usefulness, and not being in there is not a sign of lack thereof.  It's just a very convenient distribution channel.

It's not my place to tell you how to name it, I'm just concerned about the possible confusion.

But since you asked: I do not like the `cl-` prefix, as it doesn't add anything useful.  Other than that, almost anything is fine by me; I do appreciate both cleverness and directness.  Some ideas along that spectrum: `elastic-client`, `elasticlient`, `rubber-band`, `banon-round`.
